### ISSUE TITLE
TSlint v5 remove createFix function

### ISSUE THREAD

**Issue by bastienmoulia** [buzinas/tslint-eslint-rules#204]
Got the message `Warning: this.createFix is not a function` when updating tslint to 5.0.0

It's because the `createFix` function no longer exist, see https://github.com/palantir/tslint/pull/2403.

**Comment by jmlopez-rod** [comment]
[v4.0.0](https://github.com/buzinas/tslint-eslint-rules/releases/tag/v4.0.0) has been released. Let me know if there are any issues.
